
//**************************************************************************
//**
//** h2def.h : Heretic 2 : Raven Software, Corp.
//**
//** $RCSfile$
//** $Revision$
//** $Date$
//** $Author$
//**
//**************************************************************************

#ifndef __H2DEF__
#define __H2DEF__

#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include "dd_share.h"
#include "dd_api.h"
#include "dd_gl.h"
#include <malloc.h>

#pragma warning (disable:4761 4244)

//--- MSVC stuff. 
#define strcasecmp stricmp
#define strncasecmp strnicmp
//--- jk

// Version numbering changes: 200 means JHexen v1.0.
#define VERSION 199
#define VERSION_TEXT "Korax Mod v3.0"

#define DO_GUARD

// if rangecheck is undefined, most parameter validation debugging code
// will not be compiled
#ifndef NORANGECHECKING
#define RANGECHECK
#define DO_GUARD_SLOW
#endif

// Past distributions
#ifndef VER_ID
#define VER_ID "Korax"
#endif
#ifdef RANGECHECK
#define VERSIONTEXT "Version 1.0 +R "__DATE__" ("VER_ID")"
#else
#define VERSIONTEXT "Version 1.0 "__DATE__" ("VER_ID")"
#endif

// all exterior data is defined here
#include "xddefs.h"

// all important printed strings
#include "textdefs.h"

// header generated by multigen utility
#include "info.h"

#define	FINEANGLES			8192
#define	FINEMASK			(FINEANGLES-1)
#define	ANGLETOFINESHIFT	19	// 0x100000000 to 0x2000

#define MAXPLAYERS		8
#define NUM_XHAIRS		6
#define BACKUPTICS		12

//==========================================================================
//
//	Guard macros
//
//==========================================================================

#ifdef DO_GUARD
#define guard(name)		static const char *__FUNC_NAME__ = #name; try {
#define unguard			} catch (...) { DD_CoreDump(__FUNC_NAME__); throw; }
#define unguardf(msg)	} catch (...) { DD_CoreDump(__FUNC_NAME__); DD_CoreDump msg; throw; }
#else
#define guard(name)		static const char *__FUNC_NAME__ = #name; {
#define unguard			}
#define unguardf(msg)	}
#endif

#ifdef DO_GUARD_SLOW
#define guardSlow(name)		guard(name)
#define unguardSlow			unguard
#define unguardfSlow(msg)	unguardf(msg)
#else
#define guardSlow(name)		{
#define unguardSlow			}
#define unguardfSlow(msg)	}
#endif

/*
===============================================================================

						GLOBAL TYPES

===============================================================================
*/

typedef enum
{
	sk_baby,
	sk_easy,
	sk_medium,
	sk_hard,
	sk_nightmare
} skill_t;

struct ticcmd_t
{
	char		forwardmove;		// *2048 for move
	char		sidemove;			// *2048 for move
	short		angleturn;			// <<16 for angle delta
	short		consistancy;		// checks for net game
	char		lookdirdelta;		
	//byte		chatchar;
	byte		buttons;
	byte		lookfly;			// look/fly up/down/centering
	byte		arti;				// artitype_t to use
	byte        speccmd;
};

#define	BACKUPTICS				12

struct doomdata_t
{
	unsigned	checksum;					// high bit is retransmit request
	byte		retransmitfrom;				// only valid if NCMD_RETRANSMIT
	byte		starttic;
	byte		player : 4;				// from which player?
	byte		targetplayer : 4;		// the player for which this packet is meant to
	byte		numtics;
	ticcmd_t	cmds[BACKUPTICS];
};

struct doomcom_t
{
	long	id;
	short	intnum;			// DOOM executes an int to execute commands

// communication between DOOM and the driver
	short	command;		// CMD_SEND or CMD_GET
	short	remotenode;		// dest for send, set by get (-1 = no packet)
	short	datalength;		// bytes in doomdata to be sent

// info common to all nodes
	short	numnodes;		// console is allways node 0
	short	ticdup;			// 1 = no duplication, 2-5 = dup for slow nets
	short	extratics;		// 1 = send a backup tic in every packet
	short	deathmatch;		// 1 = deathmatch
	short	savegame;		// -1 = new game, 0-5 = load savegame
	short	episode;		// 1-3
	short	map;			// 1-9
	short	skill;			// 1-5

// info specific to this node
	short	consoleplayer;
	short	numplayers;
	short	angleoffset;	// 1 = left, 0 = center, -1 = right
	short	drone;			// 1 = drone

// packet data to be sent
	doomdata_t	data;
};

#define	DOOMCOM_ID		0x12345678l

extern	doomcom_t		*doomcom;
extern	doomdata_t		*netbuffer;		// points inside doomcom

#define	MAXNETNODES		16			// max computers in a game

#define	CMD_SEND	1
#define	CMD_GET		2
#define CMD_FRAG	3

#define	BT_ATTACK		1
#define	BT_USE			2
#define	BT_CHANGE		4			// if true, the next 4 bits hold weapon num
#define	BT_WEAPONMASK	(8+16+32+64)
#define	BT_WEAPONSHIFT	3

#define BT_SPECIAL		128			// game events, not really buttons
#define	BTS_SAVEMASK	(4+8+16 +32 /* [CW] 2008-11-28 : for quicksave slot */)
#define	BTS_SAVESHIFT	2
#define	BT_SPECIALMASK	3
#define	BTS_PAUSE		1			// pause the game
#define	BTS_SAVEGAME	2			// save the game at each console
// savegame slot numbers occupy the second byte of buttons

// The top 2 bits of the artifact field in the ticcmd_t struct are used
// 		as additional flags 
#define AFLAG_MASK			0x3F
#define AFLAG_SUICIDE		0x40
#define AFLAG_JUMP			0x80

//Spec Commands  added for Korax
//#define SPECCMD_DUCK        0x01
#define SPECCMD_SPELL1      0x01
#define SPECCMD_SPELL2      0x02
#define SPECCMD_SPELL3      0x04
#define SPECCMD_SPELL4      0x08
#define SPECCMD_SPELL5      0x10
#define SPECCMD_SPELL6      0x20
#define SPECCMD_SPELL7      0x40
#define SPECCMD_SPELL8      0x80

typedef enum
{
	GS_LEVEL,
	GS_INTERMISSION,
	GS_FINALE,
	GS_DEMOSCREEN
} gamestate_t;

typedef enum
{
	ga_nothing,
	ga_loadlevel,
	ga_initnew,
	ga_newgame,
	ga_loadgame,
	ga_savegame,
	ga_playdemo,
	ga_completed,
	ga_leavemap,
	ga_singlereborn,
	ga_victory,
	ga_worlddone,
	ga_screenshot
} gameaction_t;

/*
===============================================================================

							MAPOBJ DATA

===============================================================================
*/

// think_t is a function pointer to a routine to handle an actor
typedef void (*think_t) (struct thinker_t *th);

struct thinker_t
{
	thinker_t	*prev, *next;
	think_t		function;
};


struct player_t;
struct subsector_t;

struct mobj_t
{
// The data needed by the Doomsday Engine must be first, in this order!
	thinker_t		thinker;			// thinker node
	fixed_t			x,y,z;
	mobj_t			*snext, *sprev;		// links in sector (if needed)
	angle_t			angle;
	spritenum_t		sprite;				// used to find patch_t and flip value
	int				frame;				// might be ord with FF_FULLBRIGHT
	fixed_t			radius;
	int				ddflags;			// Doomday mobj flags (DDMF_*)
	subsector_t		*subsector;
	fixed_t			floorclip;		// value to use for floor clipping

// Hexen-specific data:
	player_t		*player;		// only valid if type == MT_PLAYER
	mobj_t			*bnext, *bprev;		// links in blocks (if needed)
	fixed_t			floorz, ceilingz;	// closest together of contacted secs
	fixed_t			floorpic;			// contacted sec floorpic
	fixed_t			height;		// for movement checking
	fixed_t			momx, momy, momz;	// momentums
	int				validcount;			// if == validcount, already checked
	mobjtype_t		type;
	mobjinfo_t		*info;				// &mobjinfo[mobj->type]
	int				tics;				// state tic counter
	state_t			*state;
	int				damage;			// For missiles
	int				flags;
	int				flags2;			// Heretic flags
	int				flags3;			// Remi: New flags
	int				special1;		// Special info
	int				special2;		// Special info
	int				health;
	int				movedir;		// 0-7
	int				movecount;		// when 0, select a new dir
	mobj_t			*target;		// thing being chased/attacked (or NULL)
									// also the originator for missiles
	int				reactiontime;	// if non 0, don't attack yet
									// used by player to freeze a bit after
									// teleporting
	int				threshold;		// if > 0, the target will be chased
									// no matter what (even if shot)
	int				lastlook;		// player number last looked for
	int				archiveNum;		// Identity during archive
	short			tid;			// thing identifier
	byte			special;		// special
	byte			args[5];		// special arguments
	unsigned int             experience;      // experience for RPG element
};

// each sector has a degenmobj_t in it's center for sound origin purposes
struct degenmobj_t
{
	thinker_t		thinker;		// not used for anything
	fixed_t			x,y,z;
};

// Most damage defined using HITDICE
#define HITDICE(a) ((1+(P_Random()&7))*a)

// --- mobj.flags ---

#define	MF_SPECIAL		1			// call P_SpecialThing when touched
#define	MF_SOLID		2
#define	MF_SHOOTABLE	4
#define	MF_NOSECTOR		8			// don't use the sector links
									// (invisible but touchable)
#define	MF_NOBLOCKMAP	16			// don't use the blocklinks
									// (inert but displayable)
#define	MF_AMBUSH		32
#define	MF_JUSTHIT		64			// try to attack right back
#define	MF_JUSTATTACKED	128			// take at least one step before attacking
#define	MF_SPAWNCEILING	256			// hang from ceiling instead of floor
#define	MF_NOGRAVITY	512			// don't apply gravity every tic

// movement flags
#define	MF_DROPOFF		0x400		// allow jumps from high places
#define	MF_PICKUP		0x800		// for players to pick up items
#define	MF_NOCLIP		0x1000		// player cheat
#define	MF_SLIDE		0x2000		// keep info about sliding along walls
#define	MF_FLOAT		0x4000		// allow moves to any height, no gravity
#define	MF_TELEPORT		0x8000		// don't cross lines or look at heights
#define MF_MISSILE		0x10000		// don't hit same species, explode on block

#define	MF_ALTSHADOW	0x20000		// alternate fuzzy draw
#define	MF_SHADOW		0x40000		// use fuzzy draw (shadow demons / invis)
#define	MF_NOBLOOD		0x80000		// don't bleed when shot (use puff)
#define	MF_CORPSE		0x100000	// don't stop moving halfway off a step
#define	MF_INFLOAT		0x200000	// floating to a height for a move, don't
									// auto float to target's height

#define	MF_COUNTKILL	0x400000	// count towards intermission kill total
#define	MF_ICECORPSE	0x800000	// a frozen corpse (for blasting)

#define	MF_SKULLFLY		0x1000000	// skull in flight
#define	MF_NOTDMATCH	0x2000000	// don't spawn in death match (key cards)

//#define	MF_TRANSLATION	0xc000000	// if 0x4 0x8 or 0xc, use a translation
#define	MF_TRANSLATION	0x1c000000	// use a translation table (>>MF_TRANSHIFT)
#define	MF_TRANSSHIFT	26			// table for player colormaps

// If this flag is set, the sprite is aligned with the view plane.
#define MF_BRIGHTEXPLODE	0x40000000	// Make this brightshadow when exploding.
#define MF_VIEWALIGN		0x80000000
#define MF_BRIGHTSHADOW		(MF_SHADOW|MF_ALTSHADOW)


// --- mobj.flags2 ---

#define MF2_LOGRAV			0x00000001	// alternate gravity setting
#define MF2_WINDTHRUST		0x00000002	// gets pushed around by the wind
										// specials
#define MF2_FLOORBOUNCE		0x00000004	// bounces off the floor
#define MF2_BLASTED			0x00000008	// missile will pass through ghosts
#define MF2_FLY				0x00000010	// fly mode is active
#define MF2_FLOORCLIP		0x00000020	// if feet are allowed to be clipped
#define MF2_SPAWNFLOAT		0x00000040	// spawn random float z
#define MF2_NOTELEPORT		0x00000080	// does not teleport
#define MF2_RIP				0x00000100	// missile rips through solid
										// targets
#define MF2_PUSHABLE		0x00000200	// can be pushed by other moving
										// mobjs
#define MF2_SLIDE			0x00000400	// slides against walls
#define MF2_ONMOBJ			0x00000800	// mobj is resting on top of another
										// mobj
#define MF2_PASSMOBJ		0x00001000	// Enable z block checking.  If on,
										// this flag will allow the mobj to
										// pass over/under other mobjs.
#define MF2_CANNOTPUSH		0x00002000	// cannot push other pushable mobjs
#define MF2_DROPPED			0x00004000	// dropped by a demon
#define MF2_BOSS			0x00008000	// mobj is a major boss
#define MF2_FIREDAMAGE		0x00010000	// does fire damage
#define MF2_NODMGTHRUST		0x00020000	// does not thrust target when
										// damaging
#define MF2_TELESTOMP		0x00040000	// mobj can stomp another
#define MF2_FLOATBOB		0x00080000	// use float bobbing z movement
#define MF2_DONTDRAW		0x00100000	// don't generate a vissprite
#define MF2_IMPACT			0x00200000 	// an MF_MISSILE mobj can activate
								 		// SPAC_IMPACT
#define MF2_PUSHWALL		0x00400000 	// mobj can push walls
#define MF2_MCROSS			0x00800000	// can activate monster cross lines
#define MF2_PCROSS			0x01000000	// can activate projectile cross lines
#define MF2_CANTLEAVEFLOORPIC 0x02000000 // stay within a certain floor type
#define MF2_NONSHOOTABLE	0x04000000	// mobj is totally non-shootable, 
										// but still considered solid
#define MF2_INVULNERABLE	0x08000000	// mobj is invulnerable
#define MF2_DORMANT			0x10000000	// thing is dormant
#define MF2_ICEDAMAGE		0x20000000  // does ice damage
#define MF2_SEEKERMISSILE	0x40000000	// is a seeker (for reflection)
#define MF2_REFLECTIVE		0x80000000	// reflects missiles

// --- mobj.flags2 ---

#define MF3_FRIENDLY		0x00000001	// alternate gravity setting
#define MF3_BALLSSPAWNED	0x00000002	// Heresiarch balls already spawned
#define MF3_SPEAKING		0x00000004	// actor is currently speaking

//=============================================================================

// ===== Player Class Types =====
typedef enum
{
	PCLASS_FIGHTER,
	PCLASS_CLERIC,
	PCLASS_MAGE,
	PCLASS_CORVUS,
	PCLASS_PIG,	
	//The Possessed Creatures
	PCLASS_ETTIN,
	PCLASS_AFRIT,
	PCLASS_CENTAUR,
	PCLASS_CENTAURL,
	PCLASS_ICEGUY,
	PCLASS_SERPENT,
	PCLASS_BSERPENT,
	PCLASS_REIVER,
	PCLASS_BISHOP,
	NUMCLASSES
} pclass_t;

typedef enum
{
	PST_LIVE,			// playing
	PST_DEAD,			// dead on the ground
	PST_REBORN			// ready to restart
} playerstate_t;

// psprites are scaled shapes directly on the view screen
// coordinates are given for a 320*200 view screen
typedef enum
{
	ps_weapon,
	ps_flash,
	NUMPSPRITES
} psprnum_t;

typedef struct
{
	state_t	*state;		// a NULL state means not active
	int		tics;
	fixed_t	sx, sy;
} pspdef_t;

typedef enum
{
	KKEY_1,
	KKEY_2,
	KKEY_3,
	KKEY_4,
	KKEY_5,
	KKEY_6,
	KKEY_7,
	KKEY_8,
	KKEY_9,
	KKEY_A,
	KKEY_B,
	NUMKEYS
} keytype_t;

typedef enum
{
	ARMOR_ARMOR,
	ARMOR_SHIELD,
	ARMOR_HELMET,
	ARMOR_AMULET,
	NUMARMOR
} armortype_t;

typedef enum
{
	WP_FIRST,
	WP_SECOND,
	WP_THIRD,
	WP_FOURTH,
	WP_FIFTH,
	WP_SIXTH,
	WP_SEVENTH,
	WP_EIGHTH,
	WP_NINTH,
	NUMWEAPONS
} weapontype_t;
	
typedef enum //Remi Newweaponcode
{
	WP_FIGHTER_PUNCH,
	WP_CLERIC_MACE,
	WP_MAGE_WAND3,
	WP_MAGE_WAND2,	
	WP_MAGE_WAND,
	WP_MAGE_WAND4,
	WP_CORVUS_GAUNTLETS,
	WP_CORVUS_PGAUNTLETS,
	WP_CORVUS_STAFF,
	WP_CORVUS_PSTAFF,
	WP_PIG_SNOUT,
	WP_ETTIN_MACE,
	WP_AFRIT_FIREBALL,
	WP_CENTAUR_SWORD,
	WP_CENTAURL_SWORD,
	WP_ICEGUY_MISSILE,
	WP_SERPENT_BITE,
	WP_BSERPENT_BITE,
	WP_REIVER_MELEE,
	WP_BISHOP_MELEE,
	WP_FIGHTER_AXE_G,
	WP_FIGHTER_AXE,
	WP_CLERIC_STAFF,
	WP_MAGE_CONE,
	WP_MAGE_BWAND,
	WP_CORVUS_GWAND,
	WP_CORVUS_PGWAND,
	WP_CENTAUR_SHIELD,
	WP_CENTAURL_SHIELD,
	WP_SERPENT_FIREBALL,
	WP_BSERPENT_MISSILE,
	WP_REIVER_FIREBALL,
	WP_BISHOP_MISSILES,
	WP_FIGHTER_HAMMER,
	WP_FIGHTER_HAMMER2,
	WP_CLERIC_FLAME,
	WP_MAGE_LIGHTNING,
	WP_CORVUS_CROSSBOW,
	WP_CORVUS_PCROSSBOW,
	WP_CENTAURL_MISSILE,
	WP_FIGHTER_SWORD_G,
	WP_FIGHTER_SWORD,
	WP_CLERIC_HOLY,
	WP_MAGE_STAFF,
	WP_CORVUS_MACE,
	WP_CORVUS_PMACE,
	NUMACTUALWEAPONS,
	WP_NOCHANGE,
} newweapontype_t;


typedef enum
{
	MANA_1,
	MANA_2,
	AM_GOLDWAND,
	AM_CROSSBOW,
	AM_BLASTER,
	AM_SKULLROD,
	AM_PHOENIXROD,
	AM_MACE,
	NUMMANA,
	MANA_BOTH,
	MANA_NONE
} manatype_t;

#define MAX_MANA	200

#define WPIECE1		1
#define WPIECE2		2
#define WPIECE3		4

typedef struct //Remi: New Weaponcode
{
	manatype_t mana;
	int ammouse;
	int upstate;
	int downstate;
	int readystate;
	int atkstate;
	int holdatkstate;
	int flashstate;
	pclass_t classtype;
	int bindkey;
	int PSpriteSY; //For rendering
	char name[12]; //Used for drawing weapon names
} newweaponinfo_t;

extern newweaponinfo_t NewWeaponInfo[NUMACTUALWEAPONS];

typedef enum
{
	arti_none,
	arti_invulnerability,
	arti_health,
	arti_superhealth,
	arti_healingradius,
	arti_summon,
	arti_torch,
	arti_egg,
	arti_fly,
	arti_blastradius,
	arti_poisonbag,
	arti_teleportother,
	arti_speed,
	arti_boostmana,
	arti_boostarmor,
	arti_teleport,
	// Puzzle artifacts
	arti_firstpuzzitem,
	arti_puzzskull = arti_firstpuzzitem,
	arti_puzzgembig,
	arti_puzzgemred,
	arti_puzzgemgreen1,
	arti_puzzgemgreen2,
	arti_puzzgemblue1,
	arti_puzzgemblue2,
	arti_puzzbook1,
	arti_puzzbook2,
	arti_puzzskull2,
	arti_puzzfweapon,
	arti_puzzcweapon,
	arti_puzzmweapon,
	arti_puzzgear1,
	arti_puzzgear2,
	arti_puzzgear3,
	arti_puzzgear4,
	NUMARTIFACTS
} artitype_t;

typedef enum
{
	pw_None,
	pw_invulnerability,
	pw_allmap,
	pw_infrared,
	pw_flight,
	pw_shield,
	pw_health2,
	pw_speed,
	pw_minotaur,
	pw_weaponlevel2,
	NUMPOWERS
} powertype_t;

#define	INVULNTICS (30*35)
#define	INVISTICS (60*35)
#define	INFRATICS (120*35)
#define	IRONTICS (60*35)
#define WPNLEV2TICS (40*35)
#define FLIGHTTICS (60*35)
#define SPEEDTICS (45*35)
#define MORPHTICS (40*35)
//#define MAULATORTICS (25*35)
#define MESSAGETICS (4*35)
#define BLINKTHRESHOLD (4*35)

extern int MaulatorSeconds;
#define MAULATORTICS	( (unsigned int) ((netgame || demorecording || demoplayback)? 25*35 : MaulatorSeconds*35) )

#define NUMINVENTORYSLOTS	NUMARTIFACTS

typedef struct
{
	artitype_t type;
	int count;
} inventory_t;

/*
================
=
= player_t
=
================
*/

// Extended player information.
struct player_t
{
	int			ingame;					// is this player in game?

	mobj_t		*mo;					// pointer to a mobj
	playerstate_t playerstate;
	ticcmd_t	cmd;

	pclass_t	pclass;					// player pclass type
	
	fixed_t		viewz;					// focal origin above r.z
	fixed_t		viewheight;				// base height above floor for viewz
	fixed_t		deltaviewheight;		// squat speed
	fixed_t		bob;					// bounded/scaled total momentum

	boolean		ThirdPersonView;		// Third person view?
	fixed_t		ThirdPersonOrigin[3];	// View origin in third person view
	angle_t		ThirdPersonAngle;		// Angle of the third person view
	float		ThirdPersonPitch;		// Pitch of the third person view

	int			flyheight;
	float		lookdir;				// It's now a float, for mlook. -jk
	boolean		centering;
	int			health;					// only used between levels, mo->health
										// is used during levels
	int	armorpoints[NUMARMOR];

	inventory_t	inventory[NUMINVENTORYSLOTS];
	artitype_t	readyArtifact;
	int			artifactCount;
	int 		inventorySlotNum;
	int			powers[NUMPOWERS];
	int			keys;
	int			pieces;					// Fourth Weapon pieces
	int			frags[MAXPLAYERS];		// kills of other players
	newweapontype_t	readyweapon;
	newweapontype_t	pendingweapon;		// wp_nochange if not changing
	boolean		weaponowned[NUMWEAPONS];
	int			mana[NUMMANA];
	int			attackdown, usedown;	// true if button down last tic
	int			cheats;					// bit flags

	int			refire;					// refired shots are less accurate

	int			killcount, itemcount, secretcount;		// for intermission
	char		message[80];			// hint messages
	char        message2[80];			// Remi: yup, that's right, *two* messages now!
	int			messageTics;			// counter for showing messages
	int			messageTics2;
	short		ultimateMessage;
	short		yellowMessage;
	short		yellowMessage2;
	int			damagecount, bonuscount;// for screen flashing
	int			poisoncount;			// screen flash for poison damage
	mobj_t		*poisoner;				// NULL for non-player mobjs
	mobj_t		*attacker;				// who did damage (NULL for floors)
	int			extralight;				// so gun flashes light up areas
	int			fixedcolormap;			// can be set to REDCOLORMAP, etc
	int			colormap;				// 0-3 for which color to draw player
	pspdef_t	psprites[NUMPSPRITES];	// view sprites (gun, etc)
	int			morphTics;				// player is a pig if > 0
	int			berserkTics;			// The berserker "spell" for the Fighter
	
	//Remi: Preberserk stats
	unsigned int preberserk_health;
	int preberserk_speed;
	unsigned int preberserk_strength;

	int         possTics;               // FOV effect for possession
	uint		jumpTics;				// delay the next jump for a moment
	unsigned int worldTimer;			// total time the player's been playing
	unsigned int experience;
	unsigned int money;
	int misc_viewheight;
	unsigned int hunger;
	unsigned int stamina;
	unsigned int strength;
	unsigned int agility;
	unsigned int intelligence;
	unsigned int wisdom;
	int maxhealth;
	int maxhealth_old;
	unsigned int exp_level;
	unsigned int prev_level;
	unsigned int next_level;
	unsigned int av_points;
	unsigned int maxsp_power;
	unsigned int sp_power;
	unsigned int sp_power_old;
	int speed;
	unsigned int currentspell; // Used for HUD

	// -JL- Added to player struct
	int boringmessage; //Remi: "YOU NEED TO BE LEVEL whatever TO USE MANA" boring message timer
};

#define CF_NOCLIP		1
#define	CF_GODMODE		2
#define	CF_NOMOMENTUM	4 // not really a cheat, just a debug aid

#define	SBARHEIGHT	16			// status bar height at bottom of screen

/*
===============================================================================

					GLOBAL VARIABLES

===============================================================================
*/

extern gl_export_t		gl;

#define TELEFOGHEIGHT (32*FRACUNIT)

#define MAXEVENTS 64

#define BORINGTICS 300

extern fixed_t finesine[5*FINEANGLES/4];
extern fixed_t *finecosine;

extern gameaction_t gameaction;

extern boolean paused;

extern boolean DevMaps; // true = map development mode
extern char *DevMapsDir; // development maps directory

extern boolean nomonsters; // checkparm of -nomonsters

extern boolean respawnparm; // checkparm of -respawn

extern boolean randomclass; // checkparm of -randclass

extern boolean usergame; // ok to save / end game

extern boolean ravpic; // checkparm of -ravpic

extern boolean deathmatch; // only if started as net death

extern boolean netcheat; // allow cheating during netgames

extern int		netgame; // only true if >1 player

extern player_t players[MAXPLAYERS];
extern pclass_t PlayerClass[MAXPLAYERS];
extern byte PlayerColor[MAXPLAYERS];

extern int consoleplayer; // player taking events and displaying

extern int displayplayer;

extern	boolean		singletics;			// debug flag to cancel adaptiveness

extern boolean demoplayback;

extern	gamestate_t	gamestate;
extern	skill_t		gameskill;
extern	int			gameepisode;
extern	int			gamemap;
extern 	int 		prevmap;
extern	int			levelstarttic;		// gametic at level start
extern	int			leveltime;
extern	float		gameexpmod;
			// tics in game play for par

extern int			gametic, maketic;
extern int			ticdup, server, limbo;

#define MAXDEATHMATCHSTARTS 16
extern mapthing_t *deathmatch_p;
extern mapthing_t deathmatchstarts[MAXDEATHMATCHSTARTS];

// Position indicator for cooperative net-play reborn
extern int RebornPosition;

#define MAX_PLAYER_STARTS 8
extern mapthing_t playerstarts[MAX_PLAYER_STARTS][MAXPLAYERS];

extern int mouseSensitivityX, mouseSensitivityY, usemlook, usejlook;
extern int mouseInverseY, alwaysRun;

extern boolean precache; // if true, load all graphics at level load

extern boolean singledemo; // quit after playing a demo from cmdline

extern FILE *debugfile;
extern int bodyqueslot;
extern skill_t startskill;
extern int startepisode;
extern int startmap;
extern float startexpmod;
extern boolean autostart;

extern byte netMap, netClass, netColor, netSkill, netSlot;
extern byte netDeathmatch, netNomonsters, netRandomclass, netRespawn;

// ScreenBits is currently unused.
extern int screenWidth, screenHeight, screenBits;
extern int viewph, viewpw, viewpx, viewpy;
extern int defResX, defResY, simpleSky;

extern int snd_SfxVolume, snd_MusicVolume, snd_CDVolume;

extern int act_int;

/*
===============================================================================

					GLOBAL FUNCTIONS

===============================================================================
*/


#include "z_zone.h"
#include "w_wad.h"

//----------
//BASE LEVEL
//----------
void H2_Main(void);
// not a globally visible function, just included for source reference
// calls all startup code
// parses command line options
// if not overrided, calls N_AdvanceDemo

void H2_SetFilter(int filter);

//----
//GAME
//----

void G_DeathMatchSpawnPlayer (int playernum);

void G_InitNew (skill_t skill, int episode, int map, float expmod);

void G_DeferedInitNew (skill_t skill, int episode, int map);
// can be called by the startup code or M_Responder
// a normal game starts at map 1, but a warp test can start elsewhere

void G_DeferredNewGame(skill_t skill, int expmod);

void G_DeferedPlayDemo (char *demo);
void G_DoPlayDemo (void);

void G_LoadGame(int slot);
// can be called by the startup code or M_Responder
// calls P_SetupLevel or W_EnterWorld
void G_DoLoadGame (void);

void G_SaveGame (int slot, char *description);
// called by M_Responder

void G_RecordDemo (skill_t skill, int numplayers, int episode
	, int map, char *name);
// only called by startup code

void G_PlayDemo (char *name);
void G_TimeDemo (char *name);

void G_TeleportNewMap(int map, int position);

void G_Completed(int map, int position);
//void G_ExitLevel (void);
//void G_SecretExitLevel (void);

void G_StartNewGame(skill_t skill);
void G_StartNewInit(void);

void G_WorldDone (void);

void G_Ticker (void);
boolean G_Responder (event_t *ev);

void G_ScreenShot (void);

extern boolean demoplayback, demorecording;

//-------
//SV_SAVE
//-------

#define HXS_VERSION_TEXT "HXS Ver 2.37"
#define HXS_VERSION_TEXT_LENGTH 16
#define HXS_DESCRIPTION_LENGTH 24

// [CW] 2008-11-28: moved from sv_save.cpp
#define BASE_SLOT 6
#define REBORN_SLOT 7
#define REBORN_DESCRIPTION "TEMP GAME"
//
// [CW] 2008-11-28: now.. talking about hacking the Core... :P
#define QUICK_SLOT 8
#define QUICK_DESCRIPTION "QUICK SAVE"
//

void SV_SaveGame(int slot, char *description);
void SV_SaveMap(boolean savePlayers);
void SV_LoadGame(int slot);
void SV_MapTeleport(int map, int position);
void SV_LoadMap(void);
void SV_InitBaseSlot(void);
void SV_UpdateRebornSlot(void);
void SV_ClearRebornSlot(void);
boolean SV_RebornSlotAvailable(void);
int SV_GetRebornSlot(void);

//-----
//PLAY
//-----

void P_Ticker (void);
// called by C_Ticker
// can call G_PlayerExited
// carries out all thinking of monsters and players

void P_SetupLevel (int episode, int map, int playermask, skill_t skill);
// called by W_Ticker

void P_Init (void);
// called by startup code

int P_GetMapCluster(int map);
int P_TranslateMap(int map);
int P_GetMapCDTrack(int map);
int P_GetMapWarpTrans(int map);
int P_GetMapNextMap(int map);
int P_GetMapSky1Texture(int map);
int P_GetMapSky2Texture(int map);
char *P_GetMapName(int map);
fixed_t P_GetMapSky1ScrollDelta(int map);
fixed_t P_GetMapSky2ScrollDelta(int map);
boolean P_GetMapDoubleSky(int map);
boolean P_GetMapLightning(int map);
boolean P_GetMapFadeTable(int map);
char *P_GetMapSongLump(int map);
void P_PutMapSongLump(int map, char *lumpName);
int P_GetCDStartTrack(void);
int P_GetCDEnd1Track(void);
int P_GetCDEnd2Track(void);
int P_GetCDEnd3Track(void);
int P_GetCDIntermissionTrack(void);
int P_GetCDTitleTrack(void);

//-------
//REFRESH
//-------

extern boolean setsizeneeded;

void R_SetViewSize (int blocks);
// called by M_Responder

//----
//MISC
//----
extern	int		localQuakeHappening[MAXPLAYERS];

int M_Random (void);
// returns a number from 0 to 255

extern unsigned char rndtable[256];
extern int prndindex;

#define P_Random() rndtable[(++prndindex)&0xff]
// as M_Random, but used only by the play simulation

void M_ClearRandom (void);
// fix randoms for demos
void P_SaveRandom(void);
void P_RestoreRandom(void);

void M_ScreenShot (void);

int				Argc(void);
char *			Argv(int i);
char **			ArgvPtr(int i);
int				M_CheckParm(char *check);
boolean			M_ParmExists(char *check);
void			M_SaveDefaults();
int				M_ParseCommands(char *fileName, int setdefault);
fixed_t			M_AproxDistance (fixed_t dx, fixed_t dy);
int				M_ReadFile(char const *name, byte **buffer);
int				M_ReadFileCLib(char const *name, byte **buffer);
boolean			M_WriteFile (char const *name, void *source, int length);
void			M_ExtractFileBase(char *path, char *dest);
void			M_ClearBox (fixed_t *box);
void			M_AddToBox (fixed_t *box, fixed_t x, fixed_t y);
void			M_WriteTextEsc(FILE *file, char *text);

//------------------------------
// SC_man.c
//------------------------------

void SC_Open(char *name);
void SC_OpenLump(char *name);
void SC_OpenFile(char *name);
void SC_OpenFileCLib(char *name);
void SC_Close(void);
boolean SC_GetString(void);
void SC_MustGetString(void);
void SC_MustGetStringName(char *name);
boolean SC_GetNumber(void);
void SC_MustGetNumber(void);
void SC_UnGet(void);
//boolean SC_Check(void);
boolean SC_Compare(char *text);
int SC_MatchString(char **strings);
int SC_MustMatchString(char **strings);
void SC_ScriptError(char *message);

extern char *sc_String;
extern int sc_Number;
extern int sc_Line;
extern boolean sc_End;
extern boolean sc_Crossed;
extern boolean sc_FileScripts;
extern char *sc_ScriptsDir;

//------------------------------
// SN_sonix.c
//------------------------------

enum
{
	SEQ_PLATFORM,
	SEQ_PLATFORM_HEAVY,		// same script as a normal platform
	SEQ_PLATFORM_METAL,
	SEQ_PLATFORM_CREAK,		// same script as a normal platform
	SEQ_PLATFORM_SILENCE,
	SEQ_PLATFORM_LAVA,
	SEQ_PLATFORM_WATER,
	SEQ_PLATFORM_ICE,
	SEQ_PLATFORM_EARTH,
	SEQ_PLATFORM_METAL2,
	SEQ_DOOR_STONE,
	SEQ_DOOR_HEAVY,
	SEQ_DOOR_METAL,
	SEQ_DOOR_CREAK,
	SEQ_DOOR_SILENCE,
	SEQ_DOOR_LAVA,
	SEQ_DOOR_WATER,
	SEQ_DOOR_ICE,
	SEQ_DOOR_EARTH,
	SEQ_DOOR_METAL2,
	SEQ_ESOUND_WIND,
	SEQ_NUMSEQ
};

typedef enum
{
	SEQTYPE_STONE,
	SEQTYPE_HEAVY,
	SEQTYPE_METAL,
	SEQTYPE_CREAK,
	SEQTYPE_SILENCE,
	SEQTYPE_LAVA,
	SEQTYPE_WATER,
	SEQTYPE_ICE,
	SEQTYPE_EARTH,
	SEQTYPE_METAL2,
	SEQTYPE_NUMSEQ
} seqtype_t;

void SN_InitSequenceScript(void);
void SN_StartSequence(mobj_t *mobj, int sequence);
void SN_StartSequenceName(mobj_t *mobj, char *name);
void SN_StopSequence(mobj_t *mobj);
void SN_UpdateActiveSequences(void);
void SN_StopAllSequences(void);
int SN_GetSequenceOffset(int sequence, int *sequencePtr);
void SN_ChangeNodeData(int nodeNum, int seqOffset, int delayTics, int volume,
	int currentSoundID);


typedef struct seqnode_s seqnode_t;
struct seqnode_s
{
	int *sequencePtr;
	int	sequence;
	mobj_t *mobj;
	int currentSoundID;
	int delayTics;
	int volume;
	int stopSound;
	seqnode_t *prev;
	seqnode_t *next;
};

extern int ActiveSequences;
extern seqnode_t *SequenceListHead;

//----------------------
// Interlude (IN_lude.c)
//----------------------

#define MAX_INTRMSN_MESSAGE_SIZE 1024

extern boolean intermission;
extern char ClusterMessage[MAX_INTRMSN_MESSAGE_SIZE];

void IN_Start(void);
void IN_Ticker(void);
void IN_Drawer(void);

//----------------------
// Chat mode (CT_chat.c)
//----------------------

void CT_Init(void);
void CT_Drawer(void);
boolean CT_Responder(event_t *ev);
void CT_Ticker(void);
char CT_dequeueChatChar(void);

extern boolean chatmodeon;

//--------------------
// Finale (F_finale.c)
//--------------------

void F_Drawer(void);
void F_Ticker(void);
void F_StartFinale(void);

//----------------------
// STATUS BAR (SB_bar.c)
//----------------------

extern int inv_ptr;
extern int curpos;
extern int SB_state;
void SB_Init(void);
void SB_SetClassData(void);
boolean SB_Responder(event_t *event);
void SB_Ticker(void);
void SB_Drawer(void);
void Draw_TeleportIcon(void);
void Draw_SaveIcon(void);
void Draw_LoadIcon(void);

//-----------------
// MENU (MN_menu.c)
//-----------------

void MN_Init(void);
void MN_ActivateMenu(void);
void MN_DeactivateMenu(void);
boolean MN_Responder(event_t *event);
void MN_Ticker(void);
void MN_Drawer(void);
void MN_DrTextA(char *text, int x, int y);
void MN_DrTextAYellow(char *text, int x, int y);
int MN_TextAWidth(char *text);
void MN_DrTextB(char *text, int x, int y);
int MN_TextBWidth(char *text);

// Drawing text in the current state.
void MN_DrTextA_CS(char *text, int x, int y);
void MN_DrTextAYellow_CS(char *text, int x, int y);
void MN_DrTextB_CS(char *text, int x, int y);

//========================================================================
//
// r_model.c
//
void R_SetSpriteReplacement(int sprite, char *modelname);


//========================================================================
//
// v_video.c
//
extern byte gammatable[5][256];
extern int usegamma;

//========================================================================
//
// dd_winit.c
//
void DD_Shutdown();


//========================================================================
//
// dd_main.c
//
extern int maxzone;	
extern boolean debugmode;		// checkparm of -debug
extern boolean nofullscreen;	// checkparm of -nofullscreen
extern boolean singletics;		// debug flag to cancel adaptiveness
extern FILE *debugfile;
extern event_t events[MAXEVENTS];
extern int eventhead;
extern int eventtail;

void DD_Main();
void DD_PostEvent(event_t *ev);
void DD_ProcessEvents(void);
void DD_GameLoop(void);
void DD_GameUpdate(int flags);
void AddWADFile(char *file);
void DD_CoreDump(const char *fmt, ...);
const char *DD_GetCoreDump(void);


//========================================================================
//
// dd_setup.c
//
void DD_ValidateLevel(void);

//========================================================================
//
// dd_bind.c
//
void B_Bind(event_t *event, char *command);
void B_EventConverter(char *buff, event_t *ev, boolean to_event);
int B_BindingsForCommand(char *command, char *buffer);
void B_ClearBinding(char *command);
boolean B_Responder(event_t *ev);
void B_WriteToFile(FILE *file);
void B_Shutdown();


//========================================================================
//
// dd_actn.c
//
void DD_ClearActions(void);
// The command begins with a '+' or a '-'.
// Returns true if the action was changed successfully.
int DD_ActionCommand(char *cmd, boolean has_prefix);


//========================================================================
//
// dd_3dsnd.c
//
void readline(char *buffer, int len, FILE *file);
char *firstchar(char *buffer);
void S_LoadTextureTypes();
void S_FreeTextureTypes();
int S_TextureTypeForName(char *name);
void S_CalcSectorReverbs();


//========================================================================
//
// d_net.c
//
extern int		netModel;		// The networking model.
extern int		limboplayer;
extern boolean	allow_net_traffic;	// Should net traffic be allowed?
extern boolean	map_rendered;		// Has the map been already rendered?
extern ticcmd_t	netcmds[MAXPLAYERS][BACKUPTICS];

void D_GetTicCmd(void *cmd, int player);
void D_StartNetGame();
void D_StopNetGame(boolean closing);
void D_SyncNetStart();
void NetUpdate();
void TryRunTics();


//========================================================================
//
// r_main.c
//
extern boolean	setsizeneeded;
extern int		framecount;

void R_Init (void);
void R_Update (void);
void R_RenderPlayerView (player_t *player);
void R_SetViewSize(int x, int y, int w, int h);
angle_t R_PointToAngle2 (fixed_t x1, fixed_t y1, fixed_t x2, fixed_t y2);
subsector_t *R_PointInSubsector (fixed_t x, fixed_t y);


//========================================================================
//
// r_data.c
//
int	R_FlatNumForName (char *name);
int	R_CheckTextureNumForName (char *name);
int	R_TextureNumForName (char *name);
char* R_TextureNameForNum(int num);
int R_SetFlatTranslation(int flat, int translateTo);
int R_SetTextureTranslation(int tex, int translateTo);


//========================================================================
//
// r_things.c
//
extern char	**spritenamelist;

void R_SetSpriteNameList(char **namelist);
void R_GetSpriteInfo(int sprite, int frame, spriteinfo_t *sprinfo);


//========================================================================
//
// r_draw.c
//
extern boolean BorderNeedRefresh;
extern boolean BorderTopRefresh;

void R_InitViewBorder();
void R_SetBorderGfx(char *gfx[9]);
void R_DrawViewBorder (void);
void R_DrawTopBorder (void);


//========================================================================
//
// r_model.c
//
extern boolean	useModels;

void R_InitModels(void);



//========================================================================
//
// tables.c
//
extern fixed_t finesine[5*FINEANGLES/4];
extern fixed_t *finecosine;


//========================================================================
//
// i_sound.c
//
extern boolean			use_jtSound;

void I_SetMusicDevice(int musdev);
int I_CDControl(int cmd, int parm);


// A macro to determine whether it's OK to be backwards incompatible.
#define INCOMPAT_OK		(!demorecording && !demoplayback && !netgame)

void strcatQuoted(char *dest, char *src);

#define MINIMUM_HEAP_SIZE	0x800000		//  8 meg
#define MAXIMUM_HEAP_SIZE	0x2000000		// 32 meg

enum { BLEFT, BTOP, BRIGHT, BBOTTOM };

// Networking models.
enum
{
	// Everybody communicates directly with each other.
	NETM_PEER_TO_PEER,		

	// All data goes through the server, otherwise the same as peer-to-peer.
	NETM_PURE_MULTICAST,	

	// Server knows all; answers retransmits. Clients send single packets to
	// the server, which sends them onwards to all other clients.
	NETM_MULTICAST			
};

extern int UpdateState;
extern int haloMode;


extern int myargc;
extern char **myargv;

#include "st_start.h"

#include "dd_net.h"


#include "sounds.h"

#endif // __H2DEF__
